// Street Biker: All sound, procedural Web Audio (no files), plus speech synthesis.
'use strict';
const AU={ctx:null,on:true,voiceOn:true,voices:[],hums:[]};
function noiseBuf(ctx,sec){const b=ctx.createBuffer(1,ctx.sampleRate*sec,ctx.sampleRate);const d=b.getChannelData(0);let last=0;for(let i=0;i<d.length;i++){const w=Math.random()*2-1;last=(last+0.02*w)/1.02;d[i]=w*0.5;}return b;}
function brownBuf(ctx,sec){const b=ctx.createBuffer(1,ctx.sampleRate*sec,ctx.sampleRate);const d=b.getChannelData(0);let last=0;for(let i=0;i<d.length;i++){const w=Math.random()*2-1;last=(last+0.02*w)/1.02;d[i]=last*3.5;}return b;}
function audioInit(){if(AU.ctx)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=AU.ctx=new C();AU.master=ctx.createGain();AU.master.gain.value=AU.on?0.9:0;AU.master.connect(ctx.destination);
 AU.white=noiseBuf(ctx,3);AU.brown=brownBuf(ctx,3);AU.amb=ctx.createGain();AU.amb.connect(AU.master);AU.sfx=ctx.createGain();AU.sfx.connect(AU.master);
 const load=()=>{const all=speechSynthesis.getVoices();let gb=all.filter(v=>/^en[-_]GB/i.test(v.lang)||/British|UK English|Daniel|Kate|Serena|Oliver|Arthur|Martha|Stephanie|Hazel|George|Sonia|Ryan|Libby|Thomas/i.test(v.name));if(!gb.length)gb=all.filter(v=>/^en/i.test(v.lang));AU.voices=gb;AU.voicesM=gb.filter(v=>/Daniel|Oliver|Arthur|George|Ryan|Thomas|James|Male|Man/i.test(v.name));AU.voicesF=gb.filter(v=>/Kate|Serena|Martha|Stephanie|Hazel|Sonia|Libby|Female|Woman|Susan|Fiona/i.test(v.name));};if(window.speechSynthesis){load();speechSynthesis.onvoiceschanged=load;}}
function loopNoise(buf,type,freq,Q,gain,dest){const ctx=AU.ctx;const s=ctx.createBufferSource();s.buffer=buf;s.loop=true;const f=ctx.createBiquadFilter();f.type=type;f.frequency.value=freq;f.Q.value=Q||1;const g=ctx.createGain();g.gain.value=gain;const p=ctx.createStereoPanner();s.connect(f);f.connect(g);g.connect(p);p.connect(dest||AU.amb);s.start();return{s,f,g,p};}
function stopAmb(){if(!AU.ctx)return;const t=AU.ctx.currentTime;AU.amb.gain.setTargetAtTime(0,t,0.4);const old=AU.amb;setTimeout(()=>{try{old.disconnect();}catch(e){}},1500);AU.amb=AU.ctx.createGain();AU.amb.connect(AU.master);AU.hums.forEach(h=>{try{h.o.stop();}catch(e){}});AU.hums=[];AU.roll=null;if(window.speechSynthesis)speechSynthesis.cancel();}
function startAmb(theme){if(!AU.ctx)return;const ctx=AU.ctx;if(ctx.state==='suspended')ctx.resume();stopAmb();AU.amb.gain.value=0;AU.amb.gain.setTargetAtTime(1,ctx.currentTime,0.8);AU.theme=theme;
 if(theme==='avenue'){AU.bed=loopNoise(AU.brown,'lowpass',180,0.7,0.5);AU.bed2=loopNoise(AU.white,'bandpass',900,0.5,0.03);AU.murmur=loopNoise(AU.white,'bandpass',420,1.5,0.045);
  for(let k=0;k<5;k++){const o=ctx.createOscillator();o.type='sawtooth';o.frequency.value=100;const f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=260;const g=ctx.createGain();g.gain.value=0;const p=ctx.createStereoPanner();o.connect(f);f.connect(g);g.connect(p);p.connect(AU.amb);o.start();AU.hums.push({o,g,p,f});}}
 else{AU.wind=loopNoise(AU.brown,'lowpass',320,0.5,0.32);AU.leaves=loopNoise(AU.white,'bandpass',3200,0.8,0.05);AU.murmur=loopNoise(AU.white,'bandpass',380,1.6,0.018);AU.windT=0;}
 AU.roll=loopNoise(AU.white,'lowpass',600,0.6,0,AU.sfx);AU.squeal=loopNoise(AU.white,'bandpass',2300,9,0,AU.sfx);
 AU.next={bird:0,honk:1,siren:20+Math.random()*30,squeal:8,horn:0};}
function pan(lat){return Math.max(-1,Math.min(1,lat/12));}
function doppler(g,c){const p=g.p;const rx=c.x-p.x,rz=c.z-p.z,d=Math.hypot(rx,rz)||1;const cv=c.mesh?c.v||0:0;const cq=c.mesh&&c.mesh.rotation?{x:Math.cos(-c.mesh.rotation.y),z:Math.sin(-c.mesh.rotation.y)}:{x:0,z:0};
 const vrel=((p.vx-cv*cq.x)*rx+(p.vz-cv*cq.z)*rz)/d;return{f:Math.max(0.6,Math.min(1.5,90/(90-vrel))),d,lat:-rx*Math.sin(p.a)+rz*Math.cos(p.a)};}
function honk(g,c,bus){if(!AU.ctx)return;const ctx=AU.ctx,t=ctx.currentTime;const dp=doppler(g,c);const vol=Math.min(0.5,8/(dp.d+6))*(bus?1.3:1);const dur=bus?0.7+Math.random()*0.6:0.12+Math.random()*0.35;const p=ctx.createStereoPanner();p.pan.value=pan(dp.lat);p.connect(AU.amb);
 [bus?175:390,bus?232:495].forEach(fr=>{const o=ctx.createOscillator();o.type=bus?'square':'sawtooth';o.frequency.value=fr*dp.f*(0.95+Math.random()*0.1);const f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=bus?900:1800;const gn=ctx.createGain();gn.gain.setValueAtTime(0,t);gn.gain.linearRampToValueAtTime(vol,t+0.02);gn.gain.setValueAtTime(vol,t+dur);gn.gain.linearRampToValueAtTime(0,t+dur+0.05);o.connect(f);f.connect(gn);gn.connect(p);o.start(t);o.stop(t+dur+0.1);});}
function siren(){if(!AU.ctx)return;const ctx=AU.ctx,t=ctx.currentTime,D=11;const n=400;const fc=new Float32Array(n),gc=new Float32Array(n),pc=new Float32Array(n);
 for(let i=0;i<n;i++){const u=i/(n-1);const wail=0.5+0.5*Math.sin(u*D*2*Math.PI*0.55);const dop=u<0.5?1.14-0.1*u:0.96-0.14*(u-0.5);fc[i]=(640+560*wail)*dop;const dist=Math.abs(u-0.5)*2;gc[i]=0.28*Math.pow(1-dist,2.2)*(1-0.4*Math.pow(dist,4));pc[i]=Math.sin((u-0.5)*Math.PI)*0.8;}
 const o=ctx.createOscillator();o.type='triangle';o.frequency.setValueCurveAtTime(fc,t,D);const g=ctx.createGain();g.gain.setValueCurveAtTime(gc,t,D);const p=ctx.createStereoPanner();p.pan.setValueCurveAtTime(pc,t,D);const f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=2400;o.connect(f);f.connect(g);g.connect(p);p.connect(AU.amb);o.start(t);o.stop(t+D);}
function bird(){if(!AU.ctx)return;const ctx=AU.ctx;let t=ctx.currentTime;const base=2200+Math.random()*2200,notes=1+Math.floor(Math.random()*4);const p=ctx.createStereoPanner();p.pan.value=Math.random()*2-1;const vol=0.02+Math.random()*0.05;p.connect(AU.amb);
 for(let k=0;k<notes;k++){const o=ctx.createOscillator();o.type='sine';const f0=base*(0.9+Math.random()*0.2);o.frequency.setValueAtTime(f0,t);o.frequency.exponentialRampToValueAtTime(f0*(1.1+Math.random()*0.4),t+0.06);o.frequency.exponentialRampToValueAtTime(f0*0.9,t+0.12);const g=ctx.createGain();g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+0.02);g.gain.linearRampToValueAtTime(0,t+0.13);o.connect(g);g.connect(p);o.start(t);o.stop(t+0.15);t+=0.16+Math.random()*0.12;}}
function sfxBoost(){if(!AU.ctx)return;const ctx=AU.ctx,t=ctx.currentTime;const s=ctx.createBufferSource();s.buffer=AU.white;const f=ctx.createBiquadFilter();f.type='bandpass';f.Q.value=2;f.frequency.setValueAtTime(300,t);f.frequency.exponentialRampToValueAtTime(3500,t+0.5);const g=ctx.createGain();g.gain.setValueAtTime(0.001,t);g.gain.exponentialRampToValueAtTime(0.35,t+0.12);g.gain.exponentialRampToValueAtTime(0.001,t+0.7);s.connect(f);f.connect(g);g.connect(AU.sfx);s.start(t);s.stop(t+0.8);}
function sfxHit(){if(!AU.ctx)return;const ctx=AU.ctx,t=ctx.currentTime;const o=ctx.createOscillator();o.frequency.setValueAtTime(110,t);o.frequency.exponentialRampToValueAtTime(40,t+0.25);const g=ctx.createGain();g.gain.setValueAtTime(0.5,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.3);o.connect(g);g.connect(AU.sfx);o.start(t);o.stop(t+0.32);
 const s=ctx.createBufferSource();s.buffer=AU.white;const f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=1200;const g2=ctx.createGain();g2.gain.setValueAtTime(0.3,t);g2.gain.exponentialRampToValueAtTime(0.001,t+0.15);s.connect(f);f.connect(g2);g2.connect(AU.sfx);s.start(t);s.stop(t+0.2);}
function sfxDing(big){if(!AU.ctx)return;const ctx=AU.ctx,t=ctx.currentTime;[1046,1568,big?2093:0].forEach((fr,i)=>{if(!fr)return;const o=ctx.createOscillator();o.frequency.value=fr;const g=ctx.createGain();g.gain.setValueAtTime(0.12,t+i*0.06);g.gain.exponentialRampToValueAtTime(0.001,t+i*0.06+0.5);o.connect(g);g.connect(AU.sfx);o.start(t+i*0.06);o.stop(t+i*0.06+0.55);});}
function sfxSquealShort(g,c){if(!AU.ctx)return;const ctx=AU.ctx,t=ctx.currentTime;const dp=doppler(g,c);const s=ctx.createBufferSource();s.buffer=AU.white;const f=ctx.createBiquadFilter();f.type='bandpass';f.Q.value=10;f.frequency.setValueAtTime(2600*dp.f,t);f.frequency.linearRampToValueAtTime(1900*dp.f,t+0.5);const gn=ctx.createGain();const vol=Math.min(0.25,6/(dp.d+6));gn.gain.setValueAtTime(0.001,t);gn.gain.exponentialRampToValueAtTime(vol,t+0.05);gn.gain.exponentialRampToValueAtTime(0.001,t+0.55);const p=ctx.createStereoPanner();p.pan.value=pan(dp.lat);s.connect(f);f.connect(gn);gn.connect(p);p.connect(AU.amb);s.start(t);s.stop(t+0.6);}
function audioTick(g,dt,fs,drifting){if(!AU.ctx||!AU.roll)return;const ctx=AU.ctx,t=ctx.currentTime,p=g.p;const spd=Math.abs(fs);
 AU.roll.g.gain.setTargetAtTime(Math.min(0.28,spd/27*0.28),t,0.1);AU.roll.f.frequency.setTargetAtTime(400+spd*30,t,0.1);
 AU.squeal.g.gain.setTargetAtTime(drifting?0.18:0,t,0.05);AU.squeal.f.frequency.setTargetAtTime(1800+spd*25+Math.sin(g.time*13)*150,t,0.05);
 AU.next.bird-=dt;AU.next.honk-=dt;AU.next.siren-=dt;AU.next.squeal-=dt;
 if(AU.theme==='avenue'){
  // nearest vehicles get an engine hum with doppler, distance and stereo
  const near=g.traffic.filter(c=>!c.parked).map(c=>({c,dp:doppler(g,c)})).sort((a,b)=>a.dp.d-b.dp.d).slice(0,AU.hums.length);
  AU.hums.forEach((h,i)=>{const n=near[i];if(!n){h.g.gain.setTargetAtTime(0,t,0.1);return;}const base=n.c.kind==='bus'?70:n.c.kind==='suv'?95:110;h.o.frequency.setTargetAtTime((base+n.c.v*2.5)*n.dp.f,t,0.08);h.g.gain.setTargetAtTime(Math.min(0.12,3.5/(n.dp.d+4))*(n.c.kind==='bus'?1.6:1),t,0.1);h.p.pan.setTargetAtTime(pan(n.dp.lat),t,0.1);});
  if(AU.next.honk<0){AU.next.honk=0.8+Math.random()*4;const cands=g.traffic.filter(c=>!c.parked&&Math.hypot(c.x-p.x,c.z-p.z)<90);if(cands.length){const c=pick(cands);honk(g,c,c.kind==='bus');}}
  if(AU.next.squeal<0){AU.next.squeal=6+Math.random()*14;const cands=g.traffic.filter(c=>!c.parked&&Math.hypot(c.x-p.x,c.z-p.z)<60);if(cands.length)sfxSquealShort(g,pick(cands));}
  if(AU.next.siren<0){AU.next.siren=35+Math.random()*45;siren();}
 }else{
  AU.windT-=dt;if(AU.windT<0){AU.windT=2+Math.random()*4;const w=0.18+Math.random()*0.3;AU.wind.g.gain.setTargetAtTime(w,t,1.5);AU.leaves.g.gain.setTargetAtTime(w*0.22,t,1.5);}
  if(AU.next.bird<0){AU.next.bird=0.4+Math.random()*2.6;bird();}
  if(AU.next.honk<0){AU.next.honk=10+Math.random()*18;const c={x:p.x+(Math.random()-0.5)*160,z:p.z+(Math.random()-0.5)*160,v:0};honk(g,c,false);} // distant city honk beyond the trees
 }}
function say(text,who,dist,bub){if(!window.speechSynthesis||!AU.voiceOn)return;if(speechSynthesis.speaking)return;const u=new SpeechSynthesisUtterance(text.replace(/^…/,''));if(bub){bub.life=30;u.onend=u.onerror=()=>{bub.life=Math.min(bub.life,bub.t+0.5);};}if(AU.voices.length){if(who.voice===undefined){const pool=(Math.random()<0.5&&AU.voicesM.length)?AU.voicesM:(AU.voicesF.length?AU.voicesF:AU.voices);who.voice=pool[Math.floor(Math.random()*pool.length)];}u.voice=who.voice;u.lang='en-GB';}
 if(who.pitch===undefined)who.pitch=0.75+Math.random()*0.7;u.pitch=who.pitch;u.rate=0.95+Math.random()*0.15;u.volume=Math.max(0.25,Math.min(1,1-dist/12));speechSynthesis.speak(u);}
function setSound(v){AU.on=v;$('sbtn').textContent='SFX: '+(v?'on':'off');$('sfxChk').checked=v;if(AU.ctx)AU.master.gain.setTargetAtTime(v?0.9:0,AU.ctx.currentTime,0.05);}
function setVoice(v){AU.voiceOn=v;$('vbtn').textContent='Voices: '+(v?'on':'off');$('voiceChk').checked=v;if(!v&&window.speechSynthesis)speechSynthesis.cancel();}
