// Street Biker: Tunable data: bikes, riders, tracks, chatter lines. Add content here.
'use strict';
// ---------- data ----------
const BIKES={
 red:{name:'Red Road Bike',desc:'Steel frame, drop bars, the one you actually ride. Balanced.',style:'road',frame:0xc8102e,fork:0xc8102e,rimR:0x1a1a1a,rimF:0x1a1a1a,saddle:0x111111,tape:0x111111,shirt:0x1b1b20,pants:0x4f6fa3,hair:0x2b1d12,lean:-0.3,acc:1,top:1,drift:1,turn:1},
 citi:{name:'Electric Citi Bike',desc:'Gray step-through, purple-lit basket, blue fender. Instant torque, heavy, less drift.',style:'citi',frame:0x9da3a8,fork:0x9da3a8,rimR:0x8a8f94,rimF:0x8a8f94,saddle:0x111111,tape:0x111111,shirt:0x9aa3b3,pants:0x4a6aa0,hair:0x2a1c12,lean:-0.12,acc:1.3,top:0.94,drift:0.8,turn:0.95},
 fixie:{name:'Neon Fixie',desc:'Yellow frame, green rear, orange front, orange saddle. Fastest, loosest rear, rewards clean lines.',style:'fixie',frame:0xd9ff1f,fork:0x2fb53a,rimR:0x39ff14,rimF:0xff6a1a,saddle:0xff7a1a,tape:0x39ff14,shirt:0xb8bcc4,pants:0xc9a978,hair:0x2b1d12,lean:-0.55,acc:0.9,top:1.16,drift:1.3,turn:1.12},
 lime:{name:'Lime E-Bike',desc:'White frame, green basket and fork, hub motor. Strong pull, slow to turn in.',style:'lime',frame:0xf2f2ee,fork:0x4ed92b,rimR:0x1a1a1a,rimF:0x1a1a1a,saddle:0x111111,tape:0x111111,shirt:0x6b6a4a,pants:0x8fb0d8,hair:0x2b1d12,lean:-0.15,acc:1.2,top:0.98,drift:0.85,turn:0.9}
};
const PS=0.74; // park scale: x 0 = CPW, 420 = 5th Ave; z 0 = 86th, 40/block south (before scaling)
const parkPts=[[-46,0],[-4,2],[36,18],[62,70],[56,170],[48,270],[40,370],[54,470],[44,580],[58,700],[44,820],[58,920],[100,1012],[172,1052],[252,1046],[322,1010],[350,940],[344,860],[354,760],[340,660],[350,590],[380,566],[470,562]].map(p=>[p[0]*PS,p[1]*PS]);
const TRACKS={
 park:{name:'Central Park Loop',desc:'In at 86th & CPW, south on West Drive past the Lake and Sheep Meadow, round the Pond, north on East Drive past the Zoo, out at 72nd & 5th.',
  theme:'park',width:11,closed:false,pts:parkPts,traffic:[['bike',12],['runner',6],['pedicab',3],['horse',2]],crossEvery:20,walkers:110},
 fifth:{name:'5th Avenue Sprint',desc:'96th to 51st at night. Taxis, black SUVs, sedans, buses, food carts on the corners, red lights and cross traffic.',
  theme:'avenue',width:26,closed:false,length:1620,block:36,traffic:[['cab',9],['suv',5],['sedan',6],['bus',3]],walkers:170},
 random:{name:'Random Bike Path',desc:'A new loop of park path every time. Mixed park traffic, crosswalks, no map.',
  theme:'random',width:10,closed:true,traffic:[['bike',10],['runner',6],['pedicab',2],['horse',1]],crossEvery:24,walkers:40}
};
const LINES={
 park:['…yeah so my life sucks but at least I live in New York','…are you down to go out tonight dawg','…did you see the rates today?','…and then she said the L train is a vibe. the L train is not a vibe','…I\'m not paying nineteen dollars for a smoothie, I\'ll just be tired','…he proposed at the fountain next to a guy selling churros','…my therapist said run more, so here I am, walking','…the horse looked at me like it knew about my student loans','…no I can\'t come to Jersey, I don\'t have a passport','…we matched on Hinge and it turns out we\'re in the same building','…bro that pigeon has been following me since 79th','…six years here and I\'ve never been to the Statue of Liberty','…it\'s not a hobby, it\'s a sourdough starter with a name','…pedicab wanted forty dollars for two blocks','…my roommate\'s boyfriend basically moved in and pays nothing','…if he says circle back one more time I\'m circling back to Ohio','…they only had oat milk. I said fine, I\'m not an animal','…this is the loop right? we\'ve passed that rock three times','…it\'s giving 2019','…I\'m training for the marathon by talking about the marathon','…she\'s a nepo baby but like, a nice one','…I told him the Mets thing is a personality not a team'],
 fifth:['…rent went up eleven hundred and they still haven\'t fixed the buzzer','…did you see the rates today? the ten-year is a joke','…I said close the deal, not send another deck','…forty-two hundred for a studio and the window faces a wall','…if the Fed cuts I\'m buying. if they don\'t, I\'m still buying','…he got the corner office and he still can\'t read a term sheet','…landlord raised it four hundred because the lobby got a plant','…we\'re not late, the market is early','…I\'m not touching the 6 at rush hour, get the car','…what do you mean the bonus pool is evolving','…my broker fee was more than my first car','…no. sell. I don\'t care what the chart says','…guarantor? my guarantor needs a guarantor','…it\'s a hundred and eleven square feet, I measured','…the listing said character. it has mice','…the deal died on a Friday. every deal dies on a Friday','…they want first, last, security and a kidney','…I\'m not paying for the water, I\'m paying for the zip code','…tell the analyst to fix the model or fix his résumé','…move. MOVE. some of us have a closing at four','…he said pre-war like the war was a feature','…private equity is just landlording with a deck'],
 driver:['…GPS says left, I say no','…twenty-two years on this avenue and it gets worse every day','…you\'re not getting out here, we\'re moving','…the park is closed for that, trust me','…I don\'t do Brooklyn after six','…meter\'s running, keep talking'],
 biker:['…on your left!','…is this your first lap? my ninth','…Strava says I\'m top ten on this segment','…I\'m not racing you. I\'m racing me. but also you','…clipped in, can\'t stop, sorry','…this bike cost more than my rent'],
 bus:['…stand clear of the closing doors','…this bus is now running express, deal with it']
};

const RIDERS={joe:{name:'Joe',desc:'Curly hair, dark tee, jeans, olive crossbody bag.',hair:0x3a2416,curly:true,shirt:0x3a3c3e,pants:0x3f5f96,skin:0xd9a97e,bag:0x5a6a3a,build:1.0},susie:{name:'Susie',desc:'Hair in a bun, dark tee, jeans, olive crossbody bag.',hair:0x4a2e18,bun:true,shirt:0x3a3c3e,pants:0x3f5f96,skin:0xc98f6a,bag:0x5a6a3a,build:0.88}};
